### ISSUE TITLE
02_configure_host.sh fails due to left over image pool

### ISSUE THREAD

**Issue by jtaleric** [openshift-metalkube/dev-scripts#158]
After running `make clean` I ran through the scripts again, and ran into

```
+ sudo usermod -a -G libvirt test
+ virsh pool-uuid default
+ virsh pool-define /dev/stdin
error: Failed to define pool from /dev/stdin
error: operation failed: Storage source conflict with pool: 'images'
```

To get around this, I had to destroy and undefine the left over images pool.

**Comment by hardys** [comment]
I hit this too but unfortunately didn't figure out the root cause, manually removing the images pool didn't help, I rebuilt the box with a fresh CentOS build and all was good...

Sorry should have dug further into it but needed to test other things, perhaps @markmc may have seen this?

**Comment by markmc** [comment]
No, I didn't see this myself - I only ever saw a "default" pool or no pool at all. Any idea what created the "images" pool? virt-manager/virt-install definitely create a "default" pool

**Comment by booxter** [comment]
I know it's not too helpful but I also hit `images` pool present before, and I was not able to figure out where it comes from. I just deleted it manually with `virsh` and then it started working fine.

Could it be that before we used a different name for the pool?

**Comment by markmc** [comment]
See https://www.redhat.com/archives/libvir-list/2008-August/msg00179.html for the background on why virt-manager/virt-install creates the default pool

We still don't know what creates a pool called "images" though

**Comment by russellb** [comment]
@jtaleric did you ever hit this again?

**Comment by jtaleric** [comment]
Nope.
