### ISSUE TITLE
ironic is shipping unbounded

### ISSUE THREAD

**Issue by jtaleric** [openshift-metalkube/dev-scripts#211]
Currently we ship ironic with an unbounded number of API workers. This could become an issue on the platform. We should consider bounding ironic to 12 workers (similar to how we do things in TripleO today [however, not with ironic]).

**Comment by jtaleric** [comment]
Inside the ironic container ```
[root@f13-h02-000-1029u /]# ps aux | grep ironic | wc -l
68
```

**Comment by jtaleric** [comment]
Just a heads up, we are going to capture numbers of Ironic response times with 12 workers, and compare them to the unbounded # of workers in our test env. @hardys @bfournie

**Comment by hardys** [comment]
I pushed a fix for this to https://github.com/metalkube/metalkube-ironic/pull/34, please review, I just hard coded a limit of 12 as mentioned above.

**Comment by hardys** [comment]
Closed via https://github.com/metalkube/metalkube-ironic/pull/34
