### ISSUE TITLE
Cluster not registered in cloud.openshift.com

### ISSUE THREAD

**Issue by e-minguez** [openshift-metalkube/dev-scripts#221]
It looks like the cluster deployed with the dev-scripts is not registered in cloud.openshift.com.

By some talks in the #forum-monitoring channel, it seems that in order to the cluster to be registered, the monitoring operator is failing. That is the component responsible for sending the metrics to telemetry, so if it is failing no metrics will be sent, and the cluster will not be registered.

From the events in the "openshift-monitoring" it looks like prometheus is not deployed as there are no nodes available (insufficient cpu)

**Comment by russellb** [comment]
The monitoring operator is running fine in recent deployments.  Feel free to reopen, or file a new issue if you have trouble.
