### ISSUE TITLE
kubevirt based ui not deploying

### ISSUE THREAD

**Issue by e-minguez** [openshift-metalkube/dev-scripts#251]
The kubevirt based ui is not deployed with the dev-scripts. I'm not sure what would be the procedure (maybe add more stuff to the manifests?) but I think it worth opening the issue to ensure this can be added to the deployment (it looks like the ui is this one https://github.com/kubevirt/web-ui-operator)

**Comment by e-minguez** [comment]
It looks like Karim has this covered yet https://github.com/openshift-metalkube/dev-scripts/pull/216

**Comment by hardys** [comment]
#216 merged so closing
