### ISSUE TITLE
Network interface reordering

### ISSUE THREAD

**Issue by e-minguez** [openshift-metalkube/dev-scripts#267]
I'm not sure if this is related to RHCOS version (OSTREE_VERSION=47.284) or if this can be fixed in the dev-scripts, but in my environment (3 masters, 4 nics, eth0 = provisioning network, eth1 = baremetal network, eth2 & eth3 = unused) ironic python agent and fedora get the proper nic order, but RHCOS uses eth2 as eth0 and eth3 as eth1 so the installation fails.
As a workaround, modifying the 04 script to use eth2 and eth3 instead seems to work.

**Comment by markmc** [comment]
See openshift-metalkube/dev-scripts#287 - I suspect we need to move to the rhcos ootpa channel

**Comment by hardys** [comment]
@e-minguez Can we close this now we updated to the ootpa images?

**Comment by e-minguez** [comment]
Closing it. Thanks.
