### ISSUE TITLE
Error while fetching the latest RHCOS images {malformed image url  with extra escape charater }

### ISSUE THREAD

**Issue by maveric-tellrv** [openshift-metalkube/dev-scripts#274]
While executing dev-scripts I observed Error during fetching of  latest RHCOS images,

level=debug msg=Fetching RHCOS metadata from \"https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/400.7.20190306.0/meta.json\""
level=fatal msg="failed to fetch Bootstrap Ignition Config: failed to fetch dependency of \"Bootstrap Ignition Config\": failed to fetch dependency of \"Master Machines\": failed to generate asset \"Image\": failed to fetch RHCOS metadata: incorrect HTTP response (503 Service Unavailable)"
make: *** [ocp_run] Error 1

looks like its due to extra escaping character in URL 
"https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/400.7.20190306.0/meta.json\""

**Comment by hardys** [comment]
openshift-install switched to the ootpa image/channel so I wonder if we need to rebase kni-installer to fix this.

@vrutkovs have you perhaps looked at that at all?

If not I'll attempt a rebase today and see if it helps

**Comment by vrutkovs** [comment]
There were a few issues on RHCOS metadata server, these should be resolved now.

Is this still reproducible?

**Comment by hardys** [comment]
Ok from discussion sounds like this is a known-issue which should be temporary, and https://github.com/openshift/installer/pull/1423 is the long-term fix which avoids consuming that metadata

I'll close this now but feel free to reopen should this re-occur, thanks!

**Comment by maveric-tellrv** [comment]
Installation passed successfully , this issue is no more reproducible at my end now.

**Comment by hardys** [comment]
> Installation passed successfully , this issue is no more reproducible at my end now.

Thanks for confirming! :+1:
