### ISSUE TITLE
'jq' not installed

### ISSUE THREAD

**Issue by sreichar** [openshift-metalkube/dev-scripts#276]
Attempted a baremetal deploy using some qct D51B-1u servers. 

I was able to install RHEL 7.6 one these servers after getting the failures attempt to install CentOS on this server fails.

errors from ./01_install_requirements.sh

jq used but not installed -  several failures 1 example
+++ jq -r '.builds[0]'
common.sh: line 42: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6067  100  6067    0     0  10056      0 --:--:-- --:--:-- --:--:-- 10044
curl: (23) Failed writing body (0 != 6067)

**Comment by stbenjam** [comment]
Oh there' s a bit of a chicken and an egg problem here.  We do install jq in 01, but we try to use it before it's installed in `common.sh`

**Comment by hardys** [comment]
Hmm yeah, maybe we move those RHCOS* variables to another file, there's a bunch of stuff now in common.sh that's not actually needed by all scripts

**Comment by stbenjam** [comment]
01 doesn't use anything in common.sh at all, or we could move `RHCOS` as you mentioned.

**Comment by hardys** [comment]
> 01 doesn't use anything in common.sh at all, or we could move `RHCOS*` as you mentioned.

Yeah I think the main reason it's used everywhere is the logging, we could break that out into a common_logging.sh or something
