### ISSUE TITLE
Version checks for RHEL fail in common.sh

### ISSUE THREAD

**Issue by sreichar** [openshift-metalkube/dev-scripts#277]
Check for RHEL 7 fail with RHEL 7.6 errors - several errors - 1 example

++ sudo -n uptime
+++ awk -F= '/^ID=/ { print $2 }' /etc/os-release
+++ tr -d '"'
++ [[ ! rhel =~ ^(centos|rhel)$ ]]
+++ awk -F= '/^VERSION_ID=/ { print $2 }' /etc/os-release
+++ tr -d '"'
++ [[ 7.6 -ne 7 ]]
common.sh: line 84: [[: 7.6: syntax error: invalid arithmetic operator (error token is ".6")
+++ df / --output=fstype
+++ grep -v Type
++ FSTYPE=xfs

**Comment by hardys** [comment]
Fixes landed so closing this, please reopen if any issues remain, or raise a follow-up issue
