### ISSUE TITLE
Errors with attempting to use tripleo_repos on RHEL

### ISSUE THREAD

**Issue by sreichar** [openshift-metalkube/dev-scripts#278]
tripleo-repos warnings

+ cd
+ '[' '!' -d tripleo-repos ']'
+ git clone https://git.openstack.org/openstack/tripleo-repos
Cloning into 'tripleo-repos'...
+ pushd tripleo-repos
~/tripleo-repos ~
+ sudo python setup.py install
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)

Attempted a baremetal deploy using some qct D51B-1u servers. 

I was able to install RHEL 7.6 one these servers after getting the failures attempt to install CentOS on this server fails.

errors from ./01_install_requirements.sh

tripleo-repos states rhel7.6 is unsupported

+ sudo tripleo-repos current-tripleo
WARNING: Unsupported platform 'rhel7.6' detected by tripleo-repos, centos7 will be used unless you use CLI param to change it.
WARNING: --centos-mirror was deprecated in favour of --mirror
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-
              : disabled-repos, subscription-manager
No package yum-plugin-priorities available.
Error: Nothing to do
Uploading Enabled Repositories Report
Loaded plugins: product-id, subscription-manager
Loaded plugins: product-id, subscription-manager
ERROR: Failed to install yum-plugin-priorities
['yum', 'install', '-y', 'yum-plugin-priorities']
None
Traceback (most recent call last):
  File "/bin/tripleo-repos", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tripleo_repos/main.py", line 347, in main
    _install_priorities()
  File "/usr/lib/python2.7/site-packages/tripleo_repos/main.py", line 243, in _install_priorities
    'yum-plugin-priorities'])
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['yum', 'install', '-y', 'yum-plugin-priorities']' returned non-zero exit status 1
make: *** [requirements] Error 1

**Comment by hardys** [comment]
Is this still an issue?  Can you perhaps try running the yum install manually and report why it's failing?

cc @derekhiggins as I think he may have done some testing on RHEL

**Comment by russellb** [comment]
Feel free to reopen if you're still having trouble with this.  Note that most people are still doing dev on CentOS with this repo.
