### ISSUE TITLE
dev-scripts should use the same rhcos image build that kni-install is pinned to

### ISSUE THREAD

**Issue by markmc** [openshift-metalkube/dev-scripts#287]
See also openshift-metalkube/kni-installer#37

In dev-scripts, rather than using the latest rhcos image, we should use the same one build that is hard-coded in the kni-installer repository:

```
hack/build.sh:5:RHCOS_BUILD_NAME="${RHCOS_BUILD_NAME:-400.7.20190306.0}"
```

When openshift-metalkube/kni-installer#36 lands, that also means changing the channel from maipo to ootpa

**Comment by stbenjam** [comment]
They've now removed this from `./hack/build.sh`

**Comment by stbenjam** [comment]
Looks like it moved to - https://github.com/openshift/installer/commit/f04777c0164fc5822bd68b24301ea995f559e812#diff-0631729395967455d8a8df8bc6d0eb93
