### ISSUE TITLE
Cleanup  script "Make clean"  is not removing /opt/dev-scripts directory 

### ISSUE THREAD

**Issue by maveric-tellrv** [openshift-metalkube/dev-scripts#343]
[#Minor] Make Clean script is **not** removing /opt/dev-scripts directory .

Though this issue is minor one.

When I tried to re-run the make script with user "user2" my installation fail as user2 does not have permission to write files inside /opt/dev-script/ironic folder ,as this folder is owned by pervious user "bkr" 

"make" failed with error message:
```
Writing manifest to image destination
Storing signatures
63c4f7bb2f7917d7397796f2e12dd36a8e6920a8c66716307f36afd55debb6ae
+ pushd /opt/dev-scripts/ironic/html/images
/opt/dev-scripts/ironic/html/images ~/dev-scripts
+ '[' '!' -e rhcos-410.8.20190410.0-compressed.qcow2 ']'
+ '[' '!' -e rhcos-410.8.20190410.0-compressed.qcow2.md5sum -o rhcos-410.8.20190410.0-compressed.qcow2 -nt rhcos-410.8.20190410.0-compressed.qcow2.md5sum ']'
+ ln -sf rhcos-410.8.20190410.0-compressed.qcow2 rhcos-ootpa-latest.qcow2
ln: cannot remove ‘rhcos-ootpa-latest.qcow2’: Permission denied
make: *** [ironic] Error 1
```

Content of this directory are:
```
ls -l /opt/dev-scripts/
total 8
drwxrwxr-x. 4 **bkr  bkr**    34 Apr  2 14:57 ironic
-rw-r--r--. 1 root root 3865 Apr 11 19:20 ironic_nodes.json
drwxr-xr-x. 2 root root  210 Apr 12 14:02 pool
-rw-r--r--. 1 root root  222 Apr  2 14:50 volume_pool.xml 
```
Attaching the host_cleanup logs.
[host_cleanup-2019-04-12-142513.log](https://github.com/openshift-metalkube/dev-scripts/files/3072609/host_cleanup-2019-04-12-142513.log)

**Comment by hardys** [comment]
IMHO this isn't a bug, we deliberately don't remove $WORKING_DIR or you'd have to download multi-gigabyte qcow2 files every single test iteration.

Sounds like you changed users after the initial run, so some manual cleanup seems acceptable in that case, if the alternative is causing every other user to spend more time/bandwidth during testing?

**Comment by hardys** [comment]
I guess the alternative in `common.sh` is to change this:

```
if [ ! -d "$WORKING_DIR" ]; then
  echo "Creating Working Dir"
  sudo mkdir "$WORKING_DIR"
  sudo chown "${USER}:${USER}" "$WORKING_DIR"
  chmod 755 "$WORKING_DIR"
fi
```

to 


```
if [ ! -d "$WORKING_DIR" ]; then
  echo "Creating Working Dir"
  sudo mkdir "$WORKING_DIR"
fi
sudo chown -R "${USER}:${USER}" "$WORKING_DIR"
chmod 755 "$WORKING_DIR"
```

**Comment by hardys** [comment]
I'm going to close this as I think the recursive chown is likely to break things where we've got existing files owned e.g by root and not $USER.  In the case where you choose to switch to a different non-root user I think it's acceptable to do some manual cleanup.
