### ISSUE TITLE
infinite loop 

### ISSUE THREAD

**Issue by jtaleric** [openshift-metalkube/dev-scripts#346]
If there is a networking hiccup with the setup, this loop could cause the scripts to wait forever[1].

```
+ host -t SRV _etcd-server-ssl._tcp.ostest.test.metalkube.org api.ostest.test.metalkube.org
+ echo -n .
.+ sleep 1
+ host -t SRV _etcd-server-ssl._tcp.ostest.test.metalkube.org api.ostest.test.metalkube.org
+ echo -n .
.+ sleep 1
+ host -t SRV _etcd-server-ssl._tcp.ostest.test.metalkube.org api.ostest.test.metalkube.org
+ echo -n .
.+ sleep 1
```

[1] https://github.com/openshift-metalkube/dev-scripts/blob/master/utils.sh#L162

**Comment by celebdor** [comment]
Without this baremetal just doesn't work anyway :-)

**Comment by celebdor** [comment]
But IIRC in baremetal for now people run it separately from the `make` workflow.

**Comment by celebdor** [comment]
@derekhiggins @karmab  ^^

**Comment by jtaleric** [comment]
ah? it is part of the make workflow (since it is in the 06 script)

**Comment by celebdor** [comment]
yeah, I meant additionally.

**Comment by celebdor** [comment]
https://github.com/openshift-metalkube/dev-scripts/issues/333

**Comment by jtaleric** [comment]
ah ha, #333 shouldn't be impacted here, as I am using libvirt DNS. Let'ts see if the ns1 addition gets me a success!

**Comment by russellb** [comment]
@jtaleric feel free to reopen this issue if needed.  As @celebdor notes, if DNS isn't working, the cluster isn't going to come up anyway.
