### ISSUE TITLE
"Multiple errors are preventing progress" reported during the cluster deployment process 

### ISSUE THREAD

**Issue by gklein** [openshift-metalkube/dev-scripts#386]
**Describe the bug**
Inspected several errors during the cluster deployment (virt env). The deployment was able to recover and ended successfully eventually.

**To Reproduce**
$ git rev-parse HEAD
93a8fc0af1e44df6c270e3b4b042f82c4359307f

Deploy a new cluster with "make"

**Expected/observed behavior**
Several "Multiple errors are preventing progress" appears in the log, but installation was able to recover and deploys successfully eventually.  

+ /home/kni/go/src/github.com/openshift-metalkube/kni-installer/bin/kni-install --dir ocp --log-level=debug wait-for install-complete
level=debug msg="OpenShift Installer 3e17e2e5b4cfcd2b357eb7ef866e7b57b028fce8"
level=debug msg="Built from commit 3e17e2e5b4cfcd2b357eb7ef866e7b57b028fce8"
level=info msg="Waiting up to 30m0s for the cluster at https://api.ostest.test.metalkube.org:6443 to initialize..."
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.0.0-0.ci-2019-04-17-133604: 24% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.0.0-0.ci-2019-04-17-133604: 67% complete"
level=debug msg="Still waiting for the cluster to initialize: Multiple errors are preventing progress:\n* Cluster operator authentication is still updating: missing version information for integrated-oauth-server\n* Cluster operator openshift-apiserver has not yet reported success\n* Cluster operator openshift-samples is still updating\n* Cluster operator storage has not yet reported success\n* Could not update oauthclient \"console\" (267 of 331): the server does not recognize this resource, check extension API servers"
level=debug msg="Still waiting for the cluster to initialize: Multiple errors are preventing progress:\n* Cluster operator authentication is still updating: missing version information for integrated-oauth-server\n* Cluster operator openshift-apiserver has not yet reported success\n* Cluster operator openshift-samples is still updating\n* Cluster operator storage has not yet reported success\n* Could not update oauthclient \"console\" (267 of 331): the server does not recognize this resource, check extension API servers"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.0.0-0.ci-2019-04-17-133604"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.0.0-0.ci-2019-04-17-133604: downloading update"

**Comment by russellb** [comment]
Note that all of these messages are "debug", and would not normally be visible.  If it completed successfully in the end, you can safely ignore all of this.
