### ISSUE TITLE
One master shows not ready out of 3 after several hours post deployment.

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metalkube/dev-scripts#388]
[stack@sealusa25 dev-scripts]$ oc get node
NAME       STATUS     ROLES    AGE   VERSION
master-0   Ready      master   20h   v1.13.4+1ad602308
master-1   NotReady   master   20h   v1.13.4+1ad602308
master-2   Ready      master   20h   v1.13.4+1ad602308

Checking kubelet logs:
380] Error updating node status, will retry: error getting node "master-1": Get https://api.ostest.test.metalkube.org:6443/api/v1/nodes/master-1?resourceVersion=0&timeout=10s: dial tcp 192.>
380] Error updating node status, will retry: error getting node "master-1": Get https://api.ostest.test.metalkube.org:6443/api/v1/nodes/master-1?timeout=10s: dial tcp 192.168.111.5:6443: co>
380] Error updating node status, will retry: error getting node "master-1": Get https://api.ostest.test.metalkube.org:6443/api/v1/nodes/master-1?timeout=10s: dial tcp 192.168.111.5:6443: co>
380] Error updating node status, will retry: error getting node "master-1": Get https://api.ostest.test.metalkube.org:6443/api/v1/nodes/master-1?timeout=10s: dial tcp 192.168.111.5:6443: co>
380] Error updating node status, will retry: error getting node "master-1": Get https://api.ostest.test.metalkube.org:6443/api/v1/nodes/master-1?timeout=10s: dial tcp 192.168.111.5:6443: co>
367] Unable to update node status: update node status exceeds retry count

**Comment by achuzhoy** [comment]
The issue reproduces on another setup .

**Comment by karmab** [comment]
you want to check whether there is wrong routes in the node showing as not ready

**Comment by gklein** [comment]
This issue might be related:
https://github.com/openshift-metalkube/dev-scripts/issues/344

If this is the case, it was addressed by:
https://github.com/openshift-metalkube/dev-scripts/pull/377

**Comment by russellb** [comment]
@achuzhoy Can you verify if you still see this issue this week, with #377 included?

**Comment by achuzhoy** [comment]
With the patch the issue doesn't reproduce.
Closing it.
Thanks!
