### ISSUE TITLE
internal dns doesnt work

### ISSUE THREAD

**Issue by karmab** [openshift-metalkube/dev-scripts#391]
**Describe the bug**
internal dns using $svc.$namespace.svc.cluster.local fqdns dont work, preventing communication between services of different namespaces

**To Reproduce**
Steps to reproduce the behavior, please include *all* details about the dev-scripts version (git commit SHA), any local variable overrides or other customizations, and whether you're deploying on VMs or Baremetal.
just deploy( even on virtual)

**Expected/observed behavior**
A clear and concise description of what you expected to happen and what went wrong, include details, and please try to look at relevant logs, to help us resolve the issue faster.

See https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md for some helpful steps to diagnose installer issues - please include details of any commands run here so we can gather clues to help identify the problem.

**Additional context**
Add any other context about the problem here, links to related issues etc.

**Comment by russellb** [comment]
Any more detail about which component(s) of the cluster are misbehaving? Their logs? Steps to reproduce?

**Comment by karmab** [comment]
for example,  with the following set of commands, i should get the web server but dns doesnt resolve

```
oc new-project http
oc new-app httpd-example
oc run -i --tty busybox --image=busybox --restart=Never --rm=true -- sh -c 'wget -O - httpd-example.http.svc.cluster.local:8080'
```

**Comment by karmab** [comment]
never mind, i hadnt fully tested it myself, but appears to rather be an issue with using httpd-example
